### ISSUE TITLE
How to Setup local mysql database

### ISSUE THREAD

**Issue by L30Yu** [rafe721/digital_signage_cms#1]
local mysql database did not create any tables such as users. Could you provide me more details about the database structure. Thanks

**Comment by rafe721** [comment]
[datamodel.txt](https://github.com/rafe721/digital_signage_cms/files/938910/datamodel.txt)

Hello, I have moved far beyond this model. I hope this helps. If you can let me know what your purpose is may be there is a more recent and flexible model I can help you with. Cheers and have fun.

**Comment by L30Yu** [comment]
Thank you. I am working on a project about digital signage, it need the cms server and the client player.  Your project might be a good start point for me.
